#!/bin/bash

#-----------
# Configurations
#-----------

PHPAPP_NAME=${PHPAPP_NAME-samplephp}
PHPAPP_SERVER_NAME=${PHPAPP_SERVER_NAME-samplephp.vm}
PHPAPP_PUBLIC_PATH=${PHPAPP_PUBLIC_PATH-/public}
PHPAPP_MODE=${PHPAPP_MODE-git}
PHPAPP_SERVER=${PHPAPP_SERVER-nginx}
PHPAPP_LOGS=${PHPAPP_LOGS-/var/log/$PHPAPP_SERVER}

GIT_URL=${GIT_URL-git@github.com:aforward/samplephp.git}
TARBALL_FILENAME=${TARBALL_FILENAME-./assets/myapp.tar.gz}

#-----------
# Install Script
#-----------

if [[ "$PHPAPP_MODE" == "git" ]]; then
  GIT_URL=$GIT_URL GIT_REPO_NAME=$PHPAPP_NAME ./submodules/git/install

elif [[ "$PHPAPP_MODE" == "zip" ]]; then
  TARBALL_NAME=$PHPAPP_NAME TARBALL_MODE=zip TARBALL_FILENAME=$TARBALL_FILENAME ./submodules/tarball/install
fi

if [[ "$PHPAPP_SERVER" == "nginx" ]]; then
  CONF_FILENAME=/etc/$PHPAPP_SERVER/sites-enabled/${PHPAPP_NAME}
elif [[ "$PHPAPP_SERVER" == "apache2" ]]; then
  CONF_FILENAME=/etc/$PHPAPP_SERVER/sites-enabled/${PHPAPP_NAME}.conf
fi

cp ./submodules/phpapp/files/${PHPAPP_SERVER}_conf $CONF_FILENAME
sed -i "s|@APP_NAME@|$PHPAPP_NAME|g" $CONF_FILENAME
sed -i "s|@SERVER_NAME@|$PHPAPP_SERVER_NAME|g" $CONF_FILENAME
sed -i "s|@SERVER_ROOT@|/data/${PHPAPP_NAME}${PHPAPP_PUBLIC_PATH}|g" $CONF_FILENAME
sed -i "s|@SERVER_LOGS@|$PHPAPP_LOGS|g" $CONF_FILENAME
